# One-command setup for second-brain-web-mcp.
#
# Creates the virtualenv, installs the server, generates fresh secrets, and
# writes a ready-to-run .env — so a non-technical user only needs to supply the
# path to their vault. Safe by default: it will NOT overwrite an existing .env
# unless you pass -Force.
#
#   .\scripts\setup.ps1                                  # prompts for the vault path
#   .\scripts\setup.ps1 -VaultPath "C:\Users\me\Vault"   # non-interactive
#   .\scripts\setup.ps1 -SkipInstall                     # reuse an existing .venv
#
[CmdletBinding()]
param(
    [string]$VaultPath,
    [switch]$Force,
    [switch]$SkipInstall,
    [switch]$Pause       # when launched from the app: hold the window, then close cleanly
)
$ErrorActionPreference = "Stop"

function Pause-IfAsked { if ($Pause) { Write-Host ""; [void](Read-Host "Press Enter to close this window") } }
# Catch any error, show it plainly, hold so it can be read, then close (no live prompt).
trap { Write-Host ""; Write-Host "There was a problem: $($_.Exception.Message)" -ForegroundColor Red; Pause-IfAsked; exit 1 }

$root = Split-Path -Parent $PSScriptRoot          # project root (parent of scripts\)
$envFile = Join-Path $root ".env"

# 1. Refuse to clobber an existing .env (your secrets live there).
if ((Test-Path $envFile) -and -not $Force) {
    throw ".env already exists at $envFile. Re-run with -Force to regenerate it (this replaces your current secrets)."
}

# 2. Find a Python interpreter (Windows PowerShell 5.1-safe; no null-coalescing).
$py = Get-Command python -ErrorAction SilentlyContinue
if (-not $py) { $py = Get-Command py -ErrorAction SilentlyContinue }
if (-not $py) { throw "Python 3.12+ not found on PATH. Install it from https://python.org and re-run." }

# 3. Create the venv + install the server (idempotent), with a progress bar so
#    it's obvious something is happening during the slow pip install.
$act = "Setting up Second Brain"
Write-Progress -Activity $act -Status "Creating environment..." -PercentComplete 10
$venvPy = Join-Path $root ".venv\Scripts\python.exe"
if (-not (Test-Path $venvPy)) {
    & $py.Source -m venv (Join-Path $root ".venv")
}

# Best-effort: remove corrupted leftover distributions (~*) from a previously
# interrupted install, so pip doesn't spew "Ignoring invalid distribution"
# warnings. Wrapped so it can NEVER break setup (the import check below is the
# real success gate).
$sitePkgs = Join-Path $root ".venv\Lib\site-packages"
try {
    if (Test-Path $sitePkgs) {
        Get-ChildItem $sitePkgs -Force -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like "~*" } |
            ForEach-Object { Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue }
    }
}
catch { }

if (-not $SkipInstall) {
    # pip writes harmless notices to stderr and its exit code is finicky; let it
    # run, then judge success by whether the components actually import (below).
    $ErrorActionPreference = "Continue"
    Write-Progress -Activity $act -Status "Updating the installer..." -PercentComplete 25
    & $venvPy -m pip install --upgrade pip | Out-Null
    Write-Progress -Activity $act -Status "Installing components - about a minute, please wait..." -PercentComplete 45
    Write-Host "Installing components (about a minute). Packages download below:" -ForegroundColor Cyan
    & $venvPy -m pip install -e $root
    $ErrorActionPreference = "Stop"
}

# The real success test: can the server's components be imported?
Write-Progress -Activity $act -Status "Checking the install..." -PercentComplete 80
$ErrorActionPreference = "Continue"
& $venvPy -c "import second_brain_ext, obsidian_vault_mcp" 2>$null
$impCode = $LASTEXITCODE
$ErrorActionPreference = "Stop"
if ($impCode -ne 0) { throw "The components did not install correctly. Please check your internet connection and try Step 2 again." }
Write-Progress -Activity $act -Status "Writing your settings..." -PercentComplete 85

# 4. Ask for the vault path if not supplied, and sanity-check it.
if (-not $VaultPath) {
    $VaultPath = Read-Host "Full path to your Obsidian vault (the folder of .md files)"
}
$VaultPath = $VaultPath.Trim('"').Trim()
if (-not (Test-Path $VaultPath -PathType Container)) {
    throw "Vault folder not found: '$VaultPath'. Check the path and re-run."
}

# 5. Generate the two secrets the server fails closed without.
$token = (& $venvPy -c "import secrets;print(secrets.token_hex(32))").Trim()
$pass  = (& $venvPy -c "import secrets;print(secrets.token_urlsafe(24))").Trim()

# 6. Write .env from the sanitized template values.
$lines = @(
    "# Generated by scripts\setup.ps1 - do NOT commit this file.",
    "VAULT_PATH=$VaultPath",
    "VAULT_MCP_TOKEN=$token",
    "VAULT_OAUTH_USERNAME=obsidian",
    "VAULT_OAUTH_PASSWORD=$pass",
    "VAULT_MCP_HOST=127.0.0.1",
    "VAULT_MCP_PORT=8531",
    "VAULT_MCP_PUBLIC_URL=",
    "VAULT_MCP_ALLOWED_HOSTS=",
    "OAUTH_CLIENTS_PATH=.secrets\oauth_clients.json",
    "VAULT_AUDIT_LOG_PATH=.secrets\audit.jsonl"
)
Set-Content -Path $envFile -Value $lines -Encoding utf8
New-Item -ItemType Directory -Force -Path (Join-Path $root ".secrets") | Out-Null

# Lock the secrets file down to the current user (NTFS has no honest 0600).
try {
    icacls $envFile /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null
} catch {
    Write-Warning "Could not restrict .env permissions automatically; secure it manually."
}

Write-Progress -Activity $act -Completed

Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host "  SETUP COMPLETE" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host "  Your login (save it - you type it once in Claude):"
Write-Host "    username: obsidian"
Write-Host "    password: $pass" -ForegroundColor Yellow
Write-Host ""
Write-Host "  You can CLOSE this window now and go back to the app:"
Write-Host "  click 'Step 3 - Start'. (The password also shows there.)"
Write-Host "=================================================="
Pause-IfAsked
exit 0   # deterministic success (don't leak a leftover native exit code)
