# One-command setup for second-brain-web-mcp.
#
# Creates the virtualenv, installs the server, generates fresh secrets, and
# writes a ready-to-run .env — so a non-technical user only needs to supply the
# path to their vault. Safe by default: it will NOT overwrite an existing .env
# unless you pass -Force.
#
#   .\scripts\setup.ps1                                  # prompts for the vault path
#   .\scripts\setup.ps1 -VaultPath "C:\Users\me\Vault"   # non-interactive
#   .\scripts\setup.ps1 -SkipInstall                     # reuse an existing .venv
#
[CmdletBinding()]
param(
    [string]$VaultPath,
    [switch]$Force,
    [switch]$SkipInstall
)
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot          # project root (parent of scripts\)
$envFile = Join-Path $root ".env"

# 1. Refuse to clobber an existing .env (your secrets live there).
if ((Test-Path $envFile) -and -not $Force) {
    throw ".env already exists at $envFile. Re-run with -Force to regenerate it (this replaces your current secrets)."
}

# 2. Find a Python interpreter.
$py = (Get-Command python -ErrorAction SilentlyContinue) ?? (Get-Command py -ErrorAction SilentlyContinue)
if (-not $py) { throw "Python 3.12+ not found on PATH. Install it from https://python.org and re-run." }

# 3. Create the venv + install the server (idempotent).
$venvPy = Join-Path $root ".venv\Scripts\python.exe"
if (-not (Test-Path $venvPy)) {
    Write-Host "Creating virtualenv (.venv) ..."
    & $py.Source -m venv (Join-Path $root ".venv")
}
if (-not $SkipInstall) {
    Write-Host "Installing the server (this can take a minute) ..."
    & $venvPy -m pip install --quiet --upgrade pip
    & $venvPy -m pip install --quiet -e $root
}

# 4. Ask for the vault path if not supplied, and sanity-check it.
if (-not $VaultPath) {
    $VaultPath = Read-Host "Full path to your Obsidian vault (the folder of .md files)"
}
$VaultPath = $VaultPath.Trim('"').Trim()
if (-not (Test-Path $VaultPath -PathType Container)) {
    throw "Vault folder not found: '$VaultPath'. Check the path and re-run."
}

# 5. Generate the two secrets the server fails closed without.
$token = (& $venvPy -c "import secrets;print(secrets.token_hex(32))").Trim()
$pass  = (& $venvPy -c "import secrets;print(secrets.token_urlsafe(24))").Trim()

# 6. Write .env from the sanitized template values.
$lines = @(
    "# Generated by scripts\setup.ps1 - do NOT commit this file.",
    "VAULT_PATH=$VaultPath",
    "VAULT_MCP_TOKEN=$token",
    "VAULT_OAUTH_USERNAME=obsidian",
    "VAULT_OAUTH_PASSWORD=$pass",
    "VAULT_MCP_HOST=127.0.0.1",
    "VAULT_MCP_PORT=8531",
    "VAULT_MCP_PUBLIC_URL=",
    "VAULT_MCP_ALLOWED_HOSTS=",
    "OAUTH_CLIENTS_PATH=.secrets\oauth_clients.json",
    "VAULT_AUDIT_LOG_PATH=.secrets\audit.jsonl"
)
Set-Content -Path $envFile -Value $lines -Encoding utf8
New-Item -ItemType Directory -Force -Path (Join-Path $root ".secrets") | Out-Null

# Lock the secrets file down to the current user (NTFS has no honest 0600).
try {
    icacls $envFile /inheritance:r /grant:r "$($env:USERNAME):F" | Out-Null
} catch {
    Write-Warning "Could not restrict .env permissions automatically; secure it manually."
}

Write-Host ""
Write-Host "Done. .env written to $envFile" -ForegroundColor Green
Write-Host "Your login password (save it - you'll type it once when connecting):" -ForegroundColor Yellow
Write-Host "    username: obsidian"
Write-Host "    password: $pass"
Write-Host ""
Write-Host "Next: start the server with   .\run.ps1"
Write-Host "Then connect a client to      http://127.0.0.1:8531   (see README - Quickstart)."
